### ISSUE TITLE
Can't install v0.6.1 on Windows

### ISSUE THREAD

**Issue by levz0r** [Unibeautify/vscode#111]
Hi,
I am trying to install version 0.6.1 of the extension on Windows machine, but getting the following error:
```
code --install-extension Glavin001.unibeautify-vscode
Found 'Glavin001.unibeautify-vscode' in the marketplace.
Installing...
WARNING: Promise with no error callback:4984
{ exception: null,
  error:
   Error: Invalid package C:\Users\(me)\.vscode\extensions\.glavin001.unibeautify-vscode-0.6.1\.vscode-test\stable\Visual Studio Code.app\Contents\Resources\app\node_modules.asar
       at invalidArchiveError (ELECTRON_ASAR.js:154:19)
       at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:210:16)
       at WriteStream.open (fs.js:2043:6)
       at new WriteStream (fs.js:2029:10)
       at Object.fs.createWriteStream (fs.js:1991:10)
       at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:118:238
       at new n.Class.derive._oncancel (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:55:378)
       at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:118:204
       at Object.v [as _notify] (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:48:572)
       at Object.enter (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:51:924)
       at n.Class.derive._oncancel._run (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:53:719)
       at n.Class.derive._oncancel._completed (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:53:160)
       at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:84:295
       at FSReqWrap.oncomplete (fs.js:114:15),
  promise:
   { _oncancel: null,
     _nextState: null,
     _state:
      { name: 'error',
        enter: [Function: enter],
        cancel: [Function: s],
        done: null,
        then: null,
        _completed: [Function: s],
        _error: [Function: s],
        _notify: [Function: m],
        _progress: [Function: s],
        _setCompleteValue: [Function: s],
        _setErrorValue: [Function: s] },
     _listeners: null,
     _value:
      Error: Invalid package C:\Users\(me)\.vscode\extensions\.glavin001.unibeautify-vscode-0.6.1\.vscode-test\stable\Visual Studio Code.app\Contents\Resources\app\node_modules.asar
          at invalidArchiveError (ELECTRON_ASAR.js:154:19)
          at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:210:16)
          at WriteStream.open (fs.js:2043:6)
          at new WriteStream (fs.js:2029:10)
          at Object.fs.createWriteStream (fs.js:1991:10)
          at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:118:238
          at new n.Class.derive._oncancel (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:55:378)
          at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:118:204
          at Object.v [as _notify] (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:48:572)
          at Object.enter (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:51:924)
          at n.Class.derive._oncancel._run (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:53:719)
          at n.Class.derive._oncancel._completed (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:53:160)
          at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:84:295
          at FSReqWrap.oncomplete (fs.js:114:15),
     _isException: false,
     _errorId: 4984,
     done: [Function: done],
     then: [Function: then] },
  handler: undefined,
  id: 4984,
  parent: undefined }
C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:65
if(e.stack)throw new Error(e.message+"\n\n"+e.stack);throw e},0)}}return e.prototype.addListener=function(e){var t=this;return this.listeners.push(e),function(){t._removeListener(e)}},e.prototype.emit=function(e){this.listeners.forEach(function(t){t(e)})},e.prototype._removeListener=function(e){this.listeners.splice(this.listeners.indexOf(e),1)},e.prototype.setUnexpectedErrorHandler=function(e){this.unexpectedErrorHandler=e},e.prototype.getUnexpectedErrorHandler=function(){return this.unexpectedErrorHandler},e.prototype.onUnexpectedError=function(e){this.unexpectedErrorHandler(e),this.emit(e)},e.prototype.onUnexpectedExternalError=function(e){this.unexpectedErrorHandler(e)},e}();t.ErrorHandler=s,t.errorHandler=new s,t.setUnexpectedErrorHandler=function(e){t.errorHandler.setUnexpectedErrorHandler(e)},t.onUnexpectedError=r,t.onUnexpectedExternalError=function(e){i(e)||t.errorHandler.onUnexpectedExternalError(e)},t.transformErrorForSer

Error: Invalid package C:\Users\(me)\.vscode\extensions\.glavin001.unibeautify-vscode-0.6.1\.vscode-test\stable\Visual Studio Code.app\Contents\Resources\app\node_modules.asar

Error: Invalid package C:\Users\(me)\.vscode\extensions\.glavin001.unibeautify-vscode-0.6.1\.vscode-test\stable\Visual Studio Code.app\Contents\Resources\app\node_modules.asar
    at invalidArchiveError (ELECTRON_ASAR.js:154:19)
    at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:210:16)
    at WriteStream.open (fs.js:2043:6)
    at new WriteStream (fs.js:2029:10)
    at Object.fs.createWriteStream (fs.js:1991:10)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:118:238
    at new n.Class.derive._oncancel (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:55:378)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:118:204
    at Object.v [as _notify] (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:48:572)
    at Object.enter (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:51:924)
    at n.Class.derive._oncancel._run (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:53:719)
    at n.Class.derive._oncancel._completed (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:53:160)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:84:295
    at FSReqWrap.oncomplete (fs.js:114:15)
    at Timeout._onTimeout (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:65:18)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by szeck87** [comment]
@Glavin001 do you recognize this error?

**Comment by muuvmuuv** [comment]
Can you give us more information about your system and VSCode version and also try to install the extension via the build in extension manager, I heart about cases where this fixed the problem.
