### ISSUE TITLE
Switch test runner to Jest

### ISSUE THREAD

**Issue by Glavin001** [Unibeautify/vscode#8]
Jest: https://facebook.github.io/jest/

See https://github.com/Microsoft/vscode-extension-vscode/blob/master/lib/testrunner.js for how the Mocha test runner for VSCode is implemented.

**Comment by szeck87** [comment]
I keep getting cannot find module vscode errors in the src files.
```
node --nolazy -i --inspect-brk=18784 node_modules/.bin/jest --config jest.config.js --runInBand 
Debugger listening on ws://127.0.0.1:18784/0e7e6967-b73b-4ce7-b947-c4ef11ca541b
Debugger attached.
 FAIL  test/extension.test.ts
    Test suite failed to run
    Cannot find module 'vscode' from 'index.ts'
      1 | import * as vscode from "vscode";
      2 | import { Extension } from "./Extension";
    > 3 | import { EditProvider } from "./EditProvider";
      4 | import unibeautify from "unibeautify";
      5 | import { beautifiers } from "./beautifiers";
      6 | 
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (src/index.ts:3:66)
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.806s
Ran all test suites.
Waiting for the debugger to disconnect...

```

**Comment by szeck87** [comment]
Anyone wants to take a shot at it:  https://github.com/szeck87/vscode/tree/migrate-to-jest

**Comment by szeck87** [comment]
https://github.com/strothj/vscode-gist-manager

**Comment by szeck87** [comment]
It's kind of ugly, but it works:  https://github.com/szeck87/vscode/tree/migrate-to-jest

**Comment by Glavin001** [comment]
See https://github.com/Unibeautify/vscode/pull/19
